name: Test
on:
  push:
  workflow_dispatch:
jobs:
  Sign-Apps:
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v3
     - name: Test
       run: |
            ls /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk
            
            git clone https://github.com/opa334/TrollStore
            rm TrollStore/Exploits/fastPathSign/Makefile
            cp Makefile TrollStore/Exploits/fastPathSign/Makefile
            cd TrollStore/Exploits/fastPathSign
            ls
            make
