name: Build fastPathSign
on:
  push:
  workflow_dispatch:
jobs:
  Build-fastPathSign:
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v3
     - name: Install Theos
       uses: Randomblock1/theos-action@v1.3           
     - name: Build fastPathSign
       run: make
     - name: Git Push
       run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .theos/obj/debug/fastPathSign
            git commit -m "Built fastPathSign"
            git push
