name: Test
on:
  push:
  workflow_dispatch:
jobs:
  Sign-Apps:
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v3
     - name: Install Theos
       uses: Randomblock1/theos-action@v1.3           
     - name: Test
       run: make
